// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"njk_go/internal/dal/model"
)

func newEmojiLike(db *gorm.DB, opts ...gen.DOOption) emojiLike {
	_emojiLike := emojiLike{}

	_emojiLike.emojiLikeDo.UseDB(db, opts...)
	_emojiLike.emojiLikeDo.UseModel(&model.EmojiLike{})

	tableName := _emojiLike.emojiLikeDo.TableName()
	_emojiLike.ALL = field.NewAsterisk(tableName)
	_emojiLike.ID = field.NewInt32(tableName, "id")
	_emojiLike.MessageID = field.NewString(tableName, "message_id")
	_emojiLike.UserID = field.NewString(tableName, "user_id")
	_emojiLike.FaceID = field.NewString(tableName, "face_id")

	_emojiLike.fillFieldMap()

	return _emojiLike
}

type emojiLike struct {
	emojiLikeDo emojiLikeDo

	ALL       field.Asterisk
	ID        field.Int32
	MessageID field.String
	UserID    field.String
	FaceID    field.String

	fieldMap map[string]field.Expr
}

func (e emojiLike) Table(newTableName string) *emojiLike {
	e.emojiLikeDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e emojiLike) As(alias string) *emojiLike {
	e.emojiLikeDo.DO = *(e.emojiLikeDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *emojiLike) updateTableName(table string) *emojiLike {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt32(table, "id")
	e.MessageID = field.NewString(table, "message_id")
	e.UserID = field.NewString(table, "user_id")
	e.FaceID = field.NewString(table, "face_id")

	e.fillFieldMap()

	return e
}

func (e *emojiLike) WithContext(ctx context.Context) IEmojiLikeDo {
	return e.emojiLikeDo.WithContext(ctx)
}

func (e emojiLike) TableName() string { return e.emojiLikeDo.TableName() }

func (e emojiLike) Alias() string { return e.emojiLikeDo.Alias() }

func (e emojiLike) Columns(cols ...field.Expr) gen.Columns { return e.emojiLikeDo.Columns(cols...) }

func (e *emojiLike) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *emojiLike) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 4)
	e.fieldMap["id"] = e.ID
	e.fieldMap["message_id"] = e.MessageID
	e.fieldMap["user_id"] = e.UserID
	e.fieldMap["face_id"] = e.FaceID
}

func (e emojiLike) clone(db *gorm.DB) emojiLike {
	e.emojiLikeDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e emojiLike) replaceDB(db *gorm.DB) emojiLike {
	e.emojiLikeDo.ReplaceDB(db)
	return e
}

type emojiLikeDo struct{ gen.DO }

type IEmojiLikeDo interface {
	gen.SubQuery
	Debug() IEmojiLikeDo
	WithContext(ctx context.Context) IEmojiLikeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEmojiLikeDo
	WriteDB() IEmojiLikeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEmojiLikeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEmojiLikeDo
	Not(conds ...gen.Condition) IEmojiLikeDo
	Or(conds ...gen.Condition) IEmojiLikeDo
	Select(conds ...field.Expr) IEmojiLikeDo
	Where(conds ...gen.Condition) IEmojiLikeDo
	Order(conds ...field.Expr) IEmojiLikeDo
	Distinct(cols ...field.Expr) IEmojiLikeDo
	Omit(cols ...field.Expr) IEmojiLikeDo
	Join(table schema.Tabler, on ...field.Expr) IEmojiLikeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEmojiLikeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEmojiLikeDo
	Group(cols ...field.Expr) IEmojiLikeDo
	Having(conds ...gen.Condition) IEmojiLikeDo
	Limit(limit int) IEmojiLikeDo
	Offset(offset int) IEmojiLikeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEmojiLikeDo
	Unscoped() IEmojiLikeDo
	Create(values ...*model.EmojiLike) error
	CreateInBatches(values []*model.EmojiLike, batchSize int) error
	Save(values ...*model.EmojiLike) error
	First() (*model.EmojiLike, error)
	Take() (*model.EmojiLike, error)
	Last() (*model.EmojiLike, error)
	Find() ([]*model.EmojiLike, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EmojiLike, err error)
	FindInBatches(result *[]*model.EmojiLike, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EmojiLike) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEmojiLikeDo
	Assign(attrs ...field.AssignExpr) IEmojiLikeDo
	Joins(fields ...field.RelationField) IEmojiLikeDo
	Preload(fields ...field.RelationField) IEmojiLikeDo
	FirstOrInit() (*model.EmojiLike, error)
	FirstOrCreate() (*model.EmojiLike, error)
	FindByPage(offset int, limit int) (result []*model.EmojiLike, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEmojiLikeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e emojiLikeDo) Debug() IEmojiLikeDo {
	return e.withDO(e.DO.Debug())
}

func (e emojiLikeDo) WithContext(ctx context.Context) IEmojiLikeDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e emojiLikeDo) ReadDB() IEmojiLikeDo {
	return e.Clauses(dbresolver.Read)
}

func (e emojiLikeDo) WriteDB() IEmojiLikeDo {
	return e.Clauses(dbresolver.Write)
}

func (e emojiLikeDo) Session(config *gorm.Session) IEmojiLikeDo {
	return e.withDO(e.DO.Session(config))
}

func (e emojiLikeDo) Clauses(conds ...clause.Expression) IEmojiLikeDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e emojiLikeDo) Returning(value interface{}, columns ...string) IEmojiLikeDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e emojiLikeDo) Not(conds ...gen.Condition) IEmojiLikeDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e emojiLikeDo) Or(conds ...gen.Condition) IEmojiLikeDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e emojiLikeDo) Select(conds ...field.Expr) IEmojiLikeDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e emojiLikeDo) Where(conds ...gen.Condition) IEmojiLikeDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e emojiLikeDo) Order(conds ...field.Expr) IEmojiLikeDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e emojiLikeDo) Distinct(cols ...field.Expr) IEmojiLikeDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e emojiLikeDo) Omit(cols ...field.Expr) IEmojiLikeDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e emojiLikeDo) Join(table schema.Tabler, on ...field.Expr) IEmojiLikeDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e emojiLikeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEmojiLikeDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e emojiLikeDo) RightJoin(table schema.Tabler, on ...field.Expr) IEmojiLikeDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e emojiLikeDo) Group(cols ...field.Expr) IEmojiLikeDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e emojiLikeDo) Having(conds ...gen.Condition) IEmojiLikeDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e emojiLikeDo) Limit(limit int) IEmojiLikeDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e emojiLikeDo) Offset(offset int) IEmojiLikeDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e emojiLikeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEmojiLikeDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e emojiLikeDo) Unscoped() IEmojiLikeDo {
	return e.withDO(e.DO.Unscoped())
}

func (e emojiLikeDo) Create(values ...*model.EmojiLike) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e emojiLikeDo) CreateInBatches(values []*model.EmojiLike, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e emojiLikeDo) Save(values ...*model.EmojiLike) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e emojiLikeDo) First() (*model.EmojiLike, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmojiLike), nil
	}
}

func (e emojiLikeDo) Take() (*model.EmojiLike, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmojiLike), nil
	}
}

func (e emojiLikeDo) Last() (*model.EmojiLike, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmojiLike), nil
	}
}

func (e emojiLikeDo) Find() ([]*model.EmojiLike, error) {
	result, err := e.DO.Find()
	return result.([]*model.EmojiLike), err
}

func (e emojiLikeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EmojiLike, err error) {
	buf := make([]*model.EmojiLike, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e emojiLikeDo) FindInBatches(result *[]*model.EmojiLike, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e emojiLikeDo) Attrs(attrs ...field.AssignExpr) IEmojiLikeDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e emojiLikeDo) Assign(attrs ...field.AssignExpr) IEmojiLikeDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e emojiLikeDo) Joins(fields ...field.RelationField) IEmojiLikeDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e emojiLikeDo) Preload(fields ...field.RelationField) IEmojiLikeDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e emojiLikeDo) FirstOrInit() (*model.EmojiLike, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmojiLike), nil
	}
}

func (e emojiLikeDo) FirstOrCreate() (*model.EmojiLike, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmojiLike), nil
	}
}

func (e emojiLikeDo) FindByPage(offset int, limit int) (result []*model.EmojiLike, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e emojiLikeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e emojiLikeDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e emojiLikeDo) Delete(models ...*model.EmojiLike) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *emojiLikeDo) withDO(do gen.Dao) *emojiLikeDo {
	e.DO = *do.(*gen.DO)
	return e
}
