// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"njk_go/internal/dal/model"
)

func newFace(db *gorm.DB, opts ...gen.DOOption) face {
	_face := face{}

	_face.faceDo.UseDB(db, opts...)
	_face.faceDo.UseModel(&model.Face{})

	tableName := _face.faceDo.TableName()
	_face.ALL = field.NewAsterisk(tableName)
	_face.FaceID = field.NewString(tableName, "face_id")

	_face.fillFieldMap()

	return _face
}

type face struct {
	faceDo faceDo

	ALL    field.Asterisk
	FaceID field.String

	fieldMap map[string]field.Expr
}

func (f face) Table(newTableName string) *face {
	f.faceDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f face) As(alias string) *face {
	f.faceDo.DO = *(f.faceDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *face) updateTableName(table string) *face {
	f.ALL = field.NewAsterisk(table)
	f.FaceID = field.NewString(table, "face_id")

	f.fillFieldMap()

	return f
}

func (f *face) WithContext(ctx context.Context) IFaceDo { return f.faceDo.WithContext(ctx) }

func (f face) TableName() string { return f.faceDo.TableName() }

func (f face) Alias() string { return f.faceDo.Alias() }

func (f face) Columns(cols ...field.Expr) gen.Columns { return f.faceDo.Columns(cols...) }

func (f *face) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *face) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 1)
	f.fieldMap["face_id"] = f.FaceID
}

func (f face) clone(db *gorm.DB) face {
	f.faceDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f face) replaceDB(db *gorm.DB) face {
	f.faceDo.ReplaceDB(db)
	return f
}

type faceDo struct{ gen.DO }

type IFaceDo interface {
	gen.SubQuery
	Debug() IFaceDo
	WithContext(ctx context.Context) IFaceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFaceDo
	WriteDB() IFaceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFaceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFaceDo
	Not(conds ...gen.Condition) IFaceDo
	Or(conds ...gen.Condition) IFaceDo
	Select(conds ...field.Expr) IFaceDo
	Where(conds ...gen.Condition) IFaceDo
	Order(conds ...field.Expr) IFaceDo
	Distinct(cols ...field.Expr) IFaceDo
	Omit(cols ...field.Expr) IFaceDo
	Join(table schema.Tabler, on ...field.Expr) IFaceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFaceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFaceDo
	Group(cols ...field.Expr) IFaceDo
	Having(conds ...gen.Condition) IFaceDo
	Limit(limit int) IFaceDo
	Offset(offset int) IFaceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFaceDo
	Unscoped() IFaceDo
	Create(values ...*model.Face) error
	CreateInBatches(values []*model.Face, batchSize int) error
	Save(values ...*model.Face) error
	First() (*model.Face, error)
	Take() (*model.Face, error)
	Last() (*model.Face, error)
	Find() ([]*model.Face, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Face, err error)
	FindInBatches(result *[]*model.Face, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Face) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFaceDo
	Assign(attrs ...field.AssignExpr) IFaceDo
	Joins(fields ...field.RelationField) IFaceDo
	Preload(fields ...field.RelationField) IFaceDo
	FirstOrInit() (*model.Face, error)
	FirstOrCreate() (*model.Face, error)
	FindByPage(offset int, limit int) (result []*model.Face, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFaceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f faceDo) Debug() IFaceDo {
	return f.withDO(f.DO.Debug())
}

func (f faceDo) WithContext(ctx context.Context) IFaceDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f faceDo) ReadDB() IFaceDo {
	return f.Clauses(dbresolver.Read)
}

func (f faceDo) WriteDB() IFaceDo {
	return f.Clauses(dbresolver.Write)
}

func (f faceDo) Session(config *gorm.Session) IFaceDo {
	return f.withDO(f.DO.Session(config))
}

func (f faceDo) Clauses(conds ...clause.Expression) IFaceDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f faceDo) Returning(value interface{}, columns ...string) IFaceDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f faceDo) Not(conds ...gen.Condition) IFaceDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f faceDo) Or(conds ...gen.Condition) IFaceDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f faceDo) Select(conds ...field.Expr) IFaceDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f faceDo) Where(conds ...gen.Condition) IFaceDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f faceDo) Order(conds ...field.Expr) IFaceDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f faceDo) Distinct(cols ...field.Expr) IFaceDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f faceDo) Omit(cols ...field.Expr) IFaceDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f faceDo) Join(table schema.Tabler, on ...field.Expr) IFaceDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f faceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFaceDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f faceDo) RightJoin(table schema.Tabler, on ...field.Expr) IFaceDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f faceDo) Group(cols ...field.Expr) IFaceDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f faceDo) Having(conds ...gen.Condition) IFaceDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f faceDo) Limit(limit int) IFaceDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f faceDo) Offset(offset int) IFaceDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f faceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFaceDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f faceDo) Unscoped() IFaceDo {
	return f.withDO(f.DO.Unscoped())
}

func (f faceDo) Create(values ...*model.Face) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f faceDo) CreateInBatches(values []*model.Face, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f faceDo) Save(values ...*model.Face) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f faceDo) First() (*model.Face, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Face), nil
	}
}

func (f faceDo) Take() (*model.Face, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Face), nil
	}
}

func (f faceDo) Last() (*model.Face, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Face), nil
	}
}

func (f faceDo) Find() ([]*model.Face, error) {
	result, err := f.DO.Find()
	return result.([]*model.Face), err
}

func (f faceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Face, err error) {
	buf := make([]*model.Face, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f faceDo) FindInBatches(result *[]*model.Face, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f faceDo) Attrs(attrs ...field.AssignExpr) IFaceDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f faceDo) Assign(attrs ...field.AssignExpr) IFaceDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f faceDo) Joins(fields ...field.RelationField) IFaceDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f faceDo) Preload(fields ...field.RelationField) IFaceDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f faceDo) FirstOrInit() (*model.Face, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Face), nil
	}
}

func (f faceDo) FirstOrCreate() (*model.Face, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Face), nil
	}
}

func (f faceDo) FindByPage(offset int, limit int) (result []*model.Face, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f faceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f faceDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f faceDo) Delete(models ...*model.Face) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *faceDo) withDO(do gen.Dao) *faceDo {
	f.DO = *do.(*gen.DO)
	return f
}
