// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"njk_go/internal/dal/model"
)

func newMemoryImpression(db *gorm.DB, opts ...gen.DOOption) memoryImpression {
	_memoryImpression := memoryImpression{}

	_memoryImpression.memoryImpressionDo.UseDB(db, opts...)
	_memoryImpression.memoryImpressionDo.UseModel(&model.MemoryImpression{})

	tableName := _memoryImpression.memoryImpressionDo.TableName()
	_memoryImpression.ALL = field.NewAsterisk(tableName)
	_memoryImpression.ID = field.NewInt64(tableName, "id")
	_memoryImpression.GroupID = field.NewString(tableName, "group_id")
	_memoryImpression.UserID = field.NewString(tableName, "user_id")
	_memoryImpression.MessageID = field.NewString(tableName, "message_id")
	_memoryImpression.Content = field.NewString(tableName, "content")
	_memoryImpression.ContentHash = field.NewString(tableName, "content_hash")
	_memoryImpression.Embedding = field.NewField(tableName, "embedding")
	_memoryImpression.Confidence = field.NewFloat32(tableName, "confidence")
	_memoryImpression.Version = field.NewInt32(tableName, "version")
	_memoryImpression.IsActive = field.NewBool(tableName, "is_active")
	_memoryImpression.CreatedAt = field.NewTime(tableName, "created_at")
	_memoryImpression.UpdatedAt = field.NewTime(tableName, "updated_at")

	_memoryImpression.fillFieldMap()

	return _memoryImpression
}

type memoryImpression struct {
	memoryImpressionDo memoryImpressionDo

	ALL         field.Asterisk
	ID          field.Int64
	GroupID     field.String
	UserID      field.String
	MessageID   field.String
	Content     field.String
	ContentHash field.String
	Embedding   field.Field
	Confidence  field.Float32
	Version     field.Int32
	IsActive    field.Bool
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (m memoryImpression) Table(newTableName string) *memoryImpression {
	m.memoryImpressionDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m memoryImpression) As(alias string) *memoryImpression {
	m.memoryImpressionDo.DO = *(m.memoryImpressionDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *memoryImpression) updateTableName(table string) *memoryImpression {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.GroupID = field.NewString(table, "group_id")
	m.UserID = field.NewString(table, "user_id")
	m.MessageID = field.NewString(table, "message_id")
	m.Content = field.NewString(table, "content")
	m.ContentHash = field.NewString(table, "content_hash")
	m.Embedding = field.NewField(table, "embedding")
	m.Confidence = field.NewFloat32(table, "confidence")
	m.Version = field.NewInt32(table, "version")
	m.IsActive = field.NewBool(table, "is_active")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *memoryImpression) WithContext(ctx context.Context) IMemoryImpressionDo {
	return m.memoryImpressionDo.WithContext(ctx)
}

func (m memoryImpression) TableName() string { return m.memoryImpressionDo.TableName() }

func (m memoryImpression) Alias() string { return m.memoryImpressionDo.Alias() }

func (m memoryImpression) Columns(cols ...field.Expr) gen.Columns {
	return m.memoryImpressionDo.Columns(cols...)
}

func (m *memoryImpression) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *memoryImpression) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 12)
	m.fieldMap["id"] = m.ID
	m.fieldMap["group_id"] = m.GroupID
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["message_id"] = m.MessageID
	m.fieldMap["content"] = m.Content
	m.fieldMap["content_hash"] = m.ContentHash
	m.fieldMap["embedding"] = m.Embedding
	m.fieldMap["confidence"] = m.Confidence
	m.fieldMap["version"] = m.Version
	m.fieldMap["is_active"] = m.IsActive
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m memoryImpression) clone(db *gorm.DB) memoryImpression {
	m.memoryImpressionDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m memoryImpression) replaceDB(db *gorm.DB) memoryImpression {
	m.memoryImpressionDo.ReplaceDB(db)
	return m
}

type memoryImpressionDo struct{ gen.DO }

type IMemoryImpressionDo interface {
	gen.SubQuery
	Debug() IMemoryImpressionDo
	WithContext(ctx context.Context) IMemoryImpressionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMemoryImpressionDo
	WriteDB() IMemoryImpressionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMemoryImpressionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMemoryImpressionDo
	Not(conds ...gen.Condition) IMemoryImpressionDo
	Or(conds ...gen.Condition) IMemoryImpressionDo
	Select(conds ...field.Expr) IMemoryImpressionDo
	Where(conds ...gen.Condition) IMemoryImpressionDo
	Order(conds ...field.Expr) IMemoryImpressionDo
	Distinct(cols ...field.Expr) IMemoryImpressionDo
	Omit(cols ...field.Expr) IMemoryImpressionDo
	Join(table schema.Tabler, on ...field.Expr) IMemoryImpressionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMemoryImpressionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMemoryImpressionDo
	Group(cols ...field.Expr) IMemoryImpressionDo
	Having(conds ...gen.Condition) IMemoryImpressionDo
	Limit(limit int) IMemoryImpressionDo
	Offset(offset int) IMemoryImpressionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMemoryImpressionDo
	Unscoped() IMemoryImpressionDo
	Create(values ...*model.MemoryImpression) error
	CreateInBatches(values []*model.MemoryImpression, batchSize int) error
	Save(values ...*model.MemoryImpression) error
	First() (*model.MemoryImpression, error)
	Take() (*model.MemoryImpression, error)
	Last() (*model.MemoryImpression, error)
	Find() ([]*model.MemoryImpression, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MemoryImpression, err error)
	FindInBatches(result *[]*model.MemoryImpression, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MemoryImpression) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMemoryImpressionDo
	Assign(attrs ...field.AssignExpr) IMemoryImpressionDo
	Joins(fields ...field.RelationField) IMemoryImpressionDo
	Preload(fields ...field.RelationField) IMemoryImpressionDo
	FirstOrInit() (*model.MemoryImpression, error)
	FirstOrCreate() (*model.MemoryImpression, error)
	FindByPage(offset int, limit int) (result []*model.MemoryImpression, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMemoryImpressionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m memoryImpressionDo) Debug() IMemoryImpressionDo {
	return m.withDO(m.DO.Debug())
}

func (m memoryImpressionDo) WithContext(ctx context.Context) IMemoryImpressionDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m memoryImpressionDo) ReadDB() IMemoryImpressionDo {
	return m.Clauses(dbresolver.Read)
}

func (m memoryImpressionDo) WriteDB() IMemoryImpressionDo {
	return m.Clauses(dbresolver.Write)
}

func (m memoryImpressionDo) Session(config *gorm.Session) IMemoryImpressionDo {
	return m.withDO(m.DO.Session(config))
}

func (m memoryImpressionDo) Clauses(conds ...clause.Expression) IMemoryImpressionDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m memoryImpressionDo) Returning(value interface{}, columns ...string) IMemoryImpressionDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m memoryImpressionDo) Not(conds ...gen.Condition) IMemoryImpressionDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m memoryImpressionDo) Or(conds ...gen.Condition) IMemoryImpressionDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m memoryImpressionDo) Select(conds ...field.Expr) IMemoryImpressionDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m memoryImpressionDo) Where(conds ...gen.Condition) IMemoryImpressionDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m memoryImpressionDo) Order(conds ...field.Expr) IMemoryImpressionDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m memoryImpressionDo) Distinct(cols ...field.Expr) IMemoryImpressionDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m memoryImpressionDo) Omit(cols ...field.Expr) IMemoryImpressionDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m memoryImpressionDo) Join(table schema.Tabler, on ...field.Expr) IMemoryImpressionDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m memoryImpressionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMemoryImpressionDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m memoryImpressionDo) RightJoin(table schema.Tabler, on ...field.Expr) IMemoryImpressionDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m memoryImpressionDo) Group(cols ...field.Expr) IMemoryImpressionDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m memoryImpressionDo) Having(conds ...gen.Condition) IMemoryImpressionDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m memoryImpressionDo) Limit(limit int) IMemoryImpressionDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m memoryImpressionDo) Offset(offset int) IMemoryImpressionDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m memoryImpressionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMemoryImpressionDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m memoryImpressionDo) Unscoped() IMemoryImpressionDo {
	return m.withDO(m.DO.Unscoped())
}

func (m memoryImpressionDo) Create(values ...*model.MemoryImpression) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m memoryImpressionDo) CreateInBatches(values []*model.MemoryImpression, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m memoryImpressionDo) Save(values ...*model.MemoryImpression) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m memoryImpressionDo) First() (*model.MemoryImpression, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemoryImpression), nil
	}
}

func (m memoryImpressionDo) Take() (*model.MemoryImpression, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemoryImpression), nil
	}
}

func (m memoryImpressionDo) Last() (*model.MemoryImpression, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemoryImpression), nil
	}
}

func (m memoryImpressionDo) Find() ([]*model.MemoryImpression, error) {
	result, err := m.DO.Find()
	return result.([]*model.MemoryImpression), err
}

func (m memoryImpressionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MemoryImpression, err error) {
	buf := make([]*model.MemoryImpression, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m memoryImpressionDo) FindInBatches(result *[]*model.MemoryImpression, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m memoryImpressionDo) Attrs(attrs ...field.AssignExpr) IMemoryImpressionDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m memoryImpressionDo) Assign(attrs ...field.AssignExpr) IMemoryImpressionDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m memoryImpressionDo) Joins(fields ...field.RelationField) IMemoryImpressionDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m memoryImpressionDo) Preload(fields ...field.RelationField) IMemoryImpressionDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m memoryImpressionDo) FirstOrInit() (*model.MemoryImpression, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemoryImpression), nil
	}
}

func (m memoryImpressionDo) FirstOrCreate() (*model.MemoryImpression, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemoryImpression), nil
	}
}

func (m memoryImpressionDo) FindByPage(offset int, limit int) (result []*model.MemoryImpression, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m memoryImpressionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m memoryImpressionDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m memoryImpressionDo) Delete(models ...*model.MemoryImpression) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *memoryImpressionDo) withDO(do gen.Dao) *memoryImpressionDo {
	m.DO = *do.(*gen.DO)
	return m
}
