// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"njk_go/internal/dal/model"
)

func newMemoryFact(db *gorm.DB, opts ...gen.DOOption) memoryFact {
	_memoryFact := memoryFact{}

	_memoryFact.memoryFactDo.UseDB(db, opts...)
	_memoryFact.memoryFactDo.UseModel(&model.MemoryFact{})

	tableName := _memoryFact.memoryFactDo.TableName()
	_memoryFact.ALL = field.NewAsterisk(tableName)
	_memoryFact.ID = field.NewInt64(tableName, "id")
	_memoryFact.GroupID = field.NewString(tableName, "group_id")
	_memoryFact.UserID = field.NewString(tableName, "user_id")
	_memoryFact.MessageID = field.NewString(tableName, "message_id")
	_memoryFact.Content = field.NewString(tableName, "content")
	_memoryFact.ContentHash = field.NewString(tableName, "content_hash")
	_memoryFact.Embedding = field.NewField(tableName, "embedding")
	_memoryFact.Confidence = field.NewFloat32(tableName, "confidence")
	_memoryFact.IsActive = field.NewBool(tableName, "is_active")
	_memoryFact.CreatedAt = field.NewTime(tableName, "created_at")
	_memoryFact.UpdatedAt = field.NewTime(tableName, "updated_at")

	_memoryFact.fillFieldMap()

	return _memoryFact
}

type memoryFact struct {
	memoryFactDo memoryFactDo

	ALL         field.Asterisk
	ID          field.Int64
	GroupID     field.String
	UserID      field.String
	MessageID   field.String
	Content     field.String
	ContentHash field.String
	Embedding   field.Field
	Confidence  field.Float32
	IsActive    field.Bool
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (m memoryFact) Table(newTableName string) *memoryFact {
	m.memoryFactDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m memoryFact) As(alias string) *memoryFact {
	m.memoryFactDo.DO = *(m.memoryFactDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *memoryFact) updateTableName(table string) *memoryFact {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.GroupID = field.NewString(table, "group_id")
	m.UserID = field.NewString(table, "user_id")
	m.MessageID = field.NewString(table, "message_id")
	m.Content = field.NewString(table, "content")
	m.ContentHash = field.NewString(table, "content_hash")
	m.Embedding = field.NewField(table, "embedding")
	m.Confidence = field.NewFloat32(table, "confidence")
	m.IsActive = field.NewBool(table, "is_active")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *memoryFact) WithContext(ctx context.Context) IMemoryFactDo {
	return m.memoryFactDo.WithContext(ctx)
}

func (m memoryFact) TableName() string { return m.memoryFactDo.TableName() }

func (m memoryFact) Alias() string { return m.memoryFactDo.Alias() }

func (m memoryFact) Columns(cols ...field.Expr) gen.Columns { return m.memoryFactDo.Columns(cols...) }

func (m *memoryFact) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *memoryFact) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 11)
	m.fieldMap["id"] = m.ID
	m.fieldMap["group_id"] = m.GroupID
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["message_id"] = m.MessageID
	m.fieldMap["content"] = m.Content
	m.fieldMap["content_hash"] = m.ContentHash
	m.fieldMap["embedding"] = m.Embedding
	m.fieldMap["confidence"] = m.Confidence
	m.fieldMap["is_active"] = m.IsActive
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m memoryFact) clone(db *gorm.DB) memoryFact {
	m.memoryFactDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m memoryFact) replaceDB(db *gorm.DB) memoryFact {
	m.memoryFactDo.ReplaceDB(db)
	return m
}

type memoryFactDo struct{ gen.DO }

type IMemoryFactDo interface {
	gen.SubQuery
	Debug() IMemoryFactDo
	WithContext(ctx context.Context) IMemoryFactDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMemoryFactDo
	WriteDB() IMemoryFactDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMemoryFactDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMemoryFactDo
	Not(conds ...gen.Condition) IMemoryFactDo
	Or(conds ...gen.Condition) IMemoryFactDo
	Select(conds ...field.Expr) IMemoryFactDo
	Where(conds ...gen.Condition) IMemoryFactDo
	Order(conds ...field.Expr) IMemoryFactDo
	Distinct(cols ...field.Expr) IMemoryFactDo
	Omit(cols ...field.Expr) IMemoryFactDo
	Join(table schema.Tabler, on ...field.Expr) IMemoryFactDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMemoryFactDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMemoryFactDo
	Group(cols ...field.Expr) IMemoryFactDo
	Having(conds ...gen.Condition) IMemoryFactDo
	Limit(limit int) IMemoryFactDo
	Offset(offset int) IMemoryFactDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMemoryFactDo
	Unscoped() IMemoryFactDo
	Create(values ...*model.MemoryFact) error
	CreateInBatches(values []*model.MemoryFact, batchSize int) error
	Save(values ...*model.MemoryFact) error
	First() (*model.MemoryFact, error)
	Take() (*model.MemoryFact, error)
	Last() (*model.MemoryFact, error)
	Find() ([]*model.MemoryFact, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MemoryFact, err error)
	FindInBatches(result *[]*model.MemoryFact, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MemoryFact) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMemoryFactDo
	Assign(attrs ...field.AssignExpr) IMemoryFactDo
	Joins(fields ...field.RelationField) IMemoryFactDo
	Preload(fields ...field.RelationField) IMemoryFactDo
	FirstOrInit() (*model.MemoryFact, error)
	FirstOrCreate() (*model.MemoryFact, error)
	FindByPage(offset int, limit int) (result []*model.MemoryFact, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMemoryFactDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m memoryFactDo) Debug() IMemoryFactDo {
	return m.withDO(m.DO.Debug())
}

func (m memoryFactDo) WithContext(ctx context.Context) IMemoryFactDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m memoryFactDo) ReadDB() IMemoryFactDo {
	return m.Clauses(dbresolver.Read)
}

func (m memoryFactDo) WriteDB() IMemoryFactDo {
	return m.Clauses(dbresolver.Write)
}

func (m memoryFactDo) Session(config *gorm.Session) IMemoryFactDo {
	return m.withDO(m.DO.Session(config))
}

func (m memoryFactDo) Clauses(conds ...clause.Expression) IMemoryFactDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m memoryFactDo) Returning(value interface{}, columns ...string) IMemoryFactDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m memoryFactDo) Not(conds ...gen.Condition) IMemoryFactDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m memoryFactDo) Or(conds ...gen.Condition) IMemoryFactDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m memoryFactDo) Select(conds ...field.Expr) IMemoryFactDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m memoryFactDo) Where(conds ...gen.Condition) IMemoryFactDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m memoryFactDo) Order(conds ...field.Expr) IMemoryFactDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m memoryFactDo) Distinct(cols ...field.Expr) IMemoryFactDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m memoryFactDo) Omit(cols ...field.Expr) IMemoryFactDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m memoryFactDo) Join(table schema.Tabler, on ...field.Expr) IMemoryFactDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m memoryFactDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMemoryFactDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m memoryFactDo) RightJoin(table schema.Tabler, on ...field.Expr) IMemoryFactDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m memoryFactDo) Group(cols ...field.Expr) IMemoryFactDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m memoryFactDo) Having(conds ...gen.Condition) IMemoryFactDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m memoryFactDo) Limit(limit int) IMemoryFactDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m memoryFactDo) Offset(offset int) IMemoryFactDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m memoryFactDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMemoryFactDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m memoryFactDo) Unscoped() IMemoryFactDo {
	return m.withDO(m.DO.Unscoped())
}

func (m memoryFactDo) Create(values ...*model.MemoryFact) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m memoryFactDo) CreateInBatches(values []*model.MemoryFact, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m memoryFactDo) Save(values ...*model.MemoryFact) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m memoryFactDo) First() (*model.MemoryFact, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemoryFact), nil
	}
}

func (m memoryFactDo) Take() (*model.MemoryFact, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemoryFact), nil
	}
}

func (m memoryFactDo) Last() (*model.MemoryFact, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemoryFact), nil
	}
}

func (m memoryFactDo) Find() ([]*model.MemoryFact, error) {
	result, err := m.DO.Find()
	return result.([]*model.MemoryFact), err
}

func (m memoryFactDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MemoryFact, err error) {
	buf := make([]*model.MemoryFact, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m memoryFactDo) FindInBatches(result *[]*model.MemoryFact, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m memoryFactDo) Attrs(attrs ...field.AssignExpr) IMemoryFactDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m memoryFactDo) Assign(attrs ...field.AssignExpr) IMemoryFactDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m memoryFactDo) Joins(fields ...field.RelationField) IMemoryFactDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m memoryFactDo) Preload(fields ...field.RelationField) IMemoryFactDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m memoryFactDo) FirstOrInit() (*model.MemoryFact, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemoryFact), nil
	}
}

func (m memoryFactDo) FirstOrCreate() (*model.MemoryFact, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemoryFact), nil
	}
}

func (m memoryFactDo) FindByPage(offset int, limit int) (result []*model.MemoryFact, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m memoryFactDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m memoryFactDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m memoryFactDo) Delete(models ...*model.MemoryFact) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *memoryFactDo) withDO(do gen.Dao) *memoryFactDo {
	m.DO = *do.(*gen.DO)
	return m
}
