// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAtUser = "at_user"

// AtUser mapped from table <at_user>
type AtUser struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MessageID string `gorm:"column:message_id;not null" json:"message_id"`
	UserID    string `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName AtUser's table name
func (*AtUser) TableName() string {
	return TableNameAtUser
}
