// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFace = "face"

// Face mapped from table <face>
type Face struct {
	FaceID string `gorm:"column:face_id;primaryKey" json:"face_id"`
}

// TableName Face's table name
func (*Face) TableName() string {
	return TableNameFace
}
