// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameImage = "image"

// Image mapped from table <image>
type Image struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MessageID string `gorm:"column:message_id;not null" json:"message_id"`
	ImageHash string `gorm:"column:image_hash;not null" json:"image_hash"`
}

// TableName Image's table name
func (*Image) TableName() string {
	return TableNameImage
}
