// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessage = "message"

// Message mapped from table <message>
type Message struct {
	MessageID  string    `gorm:"column:message_id;primaryKey" json:"message_id"`
	Time       time.Time `gorm:"column:time;not null" json:"time"`
	SenderID   *string   `gorm:"column:sender_id" json:"sender_id"`
	GroupID    *string   `gorm:"column:group_id" json:"group_id"`
	Card       *string   `gorm:"column:card" json:"card"`
	Text       *string   `gorm:"column:text" json:"text"`
	ReplyID    *string   `gorm:"column:reply_id" json:"reply_id"`
	RawJSON    *string   `gorm:"column:raw_json" json:"raw_json"`
	RawMessage *string   `gorm:"column:raw_message" json:"raw_message"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
