// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMsgTopic = "msg_topic"

// MsgTopic mapped from table <msg_topic>
type MsgTopic struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MessageID string `gorm:"column:message_id;not null" json:"message_id"`
	TopicID   int32  `gorm:"column:topic_id;not null" json:"topic_id"`
}

// TableName MsgTopic's table name
func (*MsgTopic) TableName() string {
	return TableNameMsgTopic
}
