// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWord = "word"

// Word mapped from table <word>
type Word struct {
	ID      int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name    string  `gorm:"column:name;not null" json:"name"`
	GroupID *string `gorm:"column:group_id" json:"group_id"`
}

// TableName Word's table name
func (*Word) TableName() string {
	return TableNameWord
}
