// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEmojiLike = "emoji_like"

// EmojiLike mapped from table <emoji_like>
type EmojiLike struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MessageID string `gorm:"column:message_id;not null" json:"message_id"`
	UserID    string `gorm:"column:user_id;not null" json:"user_id"`
	FaceID    string `gorm:"column:face_id;not null" json:"face_id"`
}

// TableName EmojiLike's table name
func (*EmojiLike) TableName() string {
	return TableNameEmojiLike
}
