// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGroup = "group"

// Group mapped from table <group>
type Group struct {
	GroupID   string `gorm:"column:group_id;primaryKey" json:"group_id"`
	GroupName string `gorm:"column:group_name;not null" json:"group_name"`
}

// TableName Group's table name
func (*Group) TableName() string {
	return TableNameGroup
}
