// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameImgWhitelist = "img_whitelist"

// ImgWhitelist mapped from table <img_whitelist>
type ImgWhitelist struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ImageHash string `gorm:"column:image_hash;not null" json:"image_hash"`
}

// TableName ImgWhitelist's table name
func (*ImgWhitelist) TableName() string {
	return TableNameImgWhitelist
}
