// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/pgvector/pgvector-go"
)

const TableNameMemoryImpression = "memory_impression"

// MemoryImpression mapped from table <memory_impression>
type MemoryImpression struct {
	ID          int64           `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GroupID     string          `gorm:"column:group_id;not null" json:"group_id"`
	UserID      string          `gorm:"column:user_id;not null" json:"user_id"`
	MessageID   *string         `gorm:"column:message_id" json:"message_id"`
	Content     string          `gorm:"column:content;not null" json:"content"`
	ContentHash string          `gorm:"column:content_hash;not null" json:"content_hash"`
	Embedding   pgvector.Vector `gorm:"column:embedding;not null" json:"embedding"`
	Confidence  float32         `gorm:"column:confidence;not null" json:"confidence"`
	Version     int32           `gorm:"column:version;not null;default:1" json:"version"`
	IsActive    bool            `gorm:"column:is_active;not null;default:true" json:"is_active"`
	CreatedAt   time.Time       `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt   time.Time       `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName MemoryImpression's table name
func (*MemoryImpression) TableName() string {
	return TableNameMemoryImpression
}
