// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMsgWord = "msg_word"

// MsgWord mapped from table <msg_word>
type MsgWord struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MessageID string `gorm:"column:message_id;not null" json:"message_id"`
	WordID    int32  `gorm:"column:word_id;not null" json:"word_id"`
}

// TableName MsgWord's table name
func (*MsgWord) TableName() string {
	return TableNameMsgWord
}
