// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTopic = "topic"

// Topic mapped from table <topic>
type Topic struct {
	ID      int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name    string  `gorm:"column:name;not null" json:"name"`
	GroupID *string `gorm:"column:group_id" json:"group_id"`
}

// TableName Topic's table name
func (*Topic) TableName() string {
	return TableNameTopic
}
