// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UserID   string `gorm:"column:user_id;primaryKey" json:"user_id"`
	Nickname string `gorm:"column:nickname;not null" json:"nickname"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
