// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"njk_go/internal/model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newAtUser(db *gorm.DB, opts ...gen.DOOption) atUser {
	_atUser := atUser{}

	_atUser.atUserDo.UseDB(db, opts...)
	_atUser.atUserDo.UseModel(&model.AtUser{})

	tableName := _atUser.atUserDo.TableName()
	_atUser.ALL = field.NewAsterisk(tableName)
	_atUser.ID = field.NewInt32(tableName, "id")
	_atUser.MessageID = field.NewString(tableName, "message_id")
	_atUser.UserID = field.NewString(tableName, "user_id")

	_atUser.fillFieldMap()

	return _atUser
}

type atUser struct {
	atUserDo atUserDo

	ALL       field.Asterisk
	ID        field.Int32
	MessageID field.String
	UserID    field.String

	fieldMap map[string]field.Expr
}

func (a atUser) Table(newTableName string) *atUser {
	a.atUserDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a atUser) As(alias string) *atUser {
	a.atUserDo.DO = *(a.atUserDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *atUser) updateTableName(table string) *atUser {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt32(table, "id")
	a.MessageID = field.NewString(table, "message_id")
	a.UserID = field.NewString(table, "user_id")

	a.fillFieldMap()

	return a
}

func (a *atUser) WithContext(ctx context.Context) IAtUserDo { return a.atUserDo.WithContext(ctx) }

func (a atUser) TableName() string { return a.atUserDo.TableName() }

func (a atUser) Alias() string { return a.atUserDo.Alias() }

func (a atUser) Columns(cols ...field.Expr) gen.Columns { return a.atUserDo.Columns(cols...) }

func (a *atUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *atUser) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 3)
	a.fieldMap["id"] = a.ID
	a.fieldMap["message_id"] = a.MessageID
	a.fieldMap["user_id"] = a.UserID
}

func (a atUser) clone(db *gorm.DB) atUser {
	a.atUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a atUser) replaceDB(db *gorm.DB) atUser {
	a.atUserDo.ReplaceDB(db)
	return a
}

type atUserDo struct{ gen.DO }

type IAtUserDo interface {
	gen.SubQuery
	Debug() IAtUserDo
	WithContext(ctx context.Context) IAtUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAtUserDo
	WriteDB() IAtUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAtUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAtUserDo
	Not(conds ...gen.Condition) IAtUserDo
	Or(conds ...gen.Condition) IAtUserDo
	Select(conds ...field.Expr) IAtUserDo
	Where(conds ...gen.Condition) IAtUserDo
	Order(conds ...field.Expr) IAtUserDo
	Distinct(cols ...field.Expr) IAtUserDo
	Omit(cols ...field.Expr) IAtUserDo
	Join(table schema.Tabler, on ...field.Expr) IAtUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAtUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAtUserDo
	Group(cols ...field.Expr) IAtUserDo
	Having(conds ...gen.Condition) IAtUserDo
	Limit(limit int) IAtUserDo
	Offset(offset int) IAtUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAtUserDo
	Unscoped() IAtUserDo
	Create(values ...*model.AtUser) error
	CreateInBatches(values []*model.AtUser, batchSize int) error
	Save(values ...*model.AtUser) error
	First() (*model.AtUser, error)
	Take() (*model.AtUser, error)
	Last() (*model.AtUser, error)
	Find() ([]*model.AtUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AtUser, err error)
	FindInBatches(result *[]*model.AtUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AtUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAtUserDo
	Assign(attrs ...field.AssignExpr) IAtUserDo
	Joins(fields ...field.RelationField) IAtUserDo
	Preload(fields ...field.RelationField) IAtUserDo
	FirstOrInit() (*model.AtUser, error)
	FirstOrCreate() (*model.AtUser, error)
	FindByPage(offset int, limit int) (result []*model.AtUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAtUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a atUserDo) Debug() IAtUserDo {
	return a.withDO(a.DO.Debug())
}

func (a atUserDo) WithContext(ctx context.Context) IAtUserDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a atUserDo) ReadDB() IAtUserDo {
	return a.Clauses(dbresolver.Read)
}

func (a atUserDo) WriteDB() IAtUserDo {
	return a.Clauses(dbresolver.Write)
}

func (a atUserDo) Session(config *gorm.Session) IAtUserDo {
	return a.withDO(a.DO.Session(config))
}

func (a atUserDo) Clauses(conds ...clause.Expression) IAtUserDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a atUserDo) Returning(value interface{}, columns ...string) IAtUserDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a atUserDo) Not(conds ...gen.Condition) IAtUserDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a atUserDo) Or(conds ...gen.Condition) IAtUserDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a atUserDo) Select(conds ...field.Expr) IAtUserDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a atUserDo) Where(conds ...gen.Condition) IAtUserDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a atUserDo) Order(conds ...field.Expr) IAtUserDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a atUserDo) Distinct(cols ...field.Expr) IAtUserDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a atUserDo) Omit(cols ...field.Expr) IAtUserDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a atUserDo) Join(table schema.Tabler, on ...field.Expr) IAtUserDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a atUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAtUserDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a atUserDo) RightJoin(table schema.Tabler, on ...field.Expr) IAtUserDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a atUserDo) Group(cols ...field.Expr) IAtUserDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a atUserDo) Having(conds ...gen.Condition) IAtUserDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a atUserDo) Limit(limit int) IAtUserDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a atUserDo) Offset(offset int) IAtUserDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a atUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAtUserDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a atUserDo) Unscoped() IAtUserDo {
	return a.withDO(a.DO.Unscoped())
}

func (a atUserDo) Create(values ...*model.AtUser) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a atUserDo) CreateInBatches(values []*model.AtUser, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a atUserDo) Save(values ...*model.AtUser) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a atUserDo) First() (*model.AtUser, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AtUser), nil
	}
}

func (a atUserDo) Take() (*model.AtUser, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AtUser), nil
	}
}

func (a atUserDo) Last() (*model.AtUser, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AtUser), nil
	}
}

func (a atUserDo) Find() ([]*model.AtUser, error) {
	result, err := a.DO.Find()
	return result.([]*model.AtUser), err
}

func (a atUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AtUser, err error) {
	buf := make([]*model.AtUser, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a atUserDo) FindInBatches(result *[]*model.AtUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a atUserDo) Attrs(attrs ...field.AssignExpr) IAtUserDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a atUserDo) Assign(attrs ...field.AssignExpr) IAtUserDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a atUserDo) Joins(fields ...field.RelationField) IAtUserDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a atUserDo) Preload(fields ...field.RelationField) IAtUserDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a atUserDo) FirstOrInit() (*model.AtUser, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AtUser), nil
	}
}

func (a atUserDo) FirstOrCreate() (*model.AtUser, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AtUser), nil
	}
}

func (a atUserDo) FindByPage(offset int, limit int) (result []*model.AtUser, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a atUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a atUserDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a atUserDo) Delete(models ...*model.AtUser) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *atUserDo) withDO(do gen.Dao) *atUserDo {
	a.DO = *do.(*gen.DO)
	return a
}
