// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q            = new(Query)
	AtUser       *atUser
	Group        *group
	Image        *image
	ImgWhitelist *imgWhitelist
	Message      *message
	MsgTopic     *msgTopic
	MsgWord      *msgWord
	Topic        *topic
	User         *user
	Word         *word
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AtUser = &Q.AtUser
	Group = &Q.Group
	Image = &Q.Image
	ImgWhitelist = &Q.ImgWhitelist
	Message = &Q.Message
	MsgTopic = &Q.MsgTopic
	MsgWord = &Q.MsgWord
	Topic = &Q.Topic
	User = &Q.User
	Word = &Q.Word
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		AtUser:       newAtUser(db, opts...),
		Group:        newGroup(db, opts...),
		Image:        newImage(db, opts...),
		ImgWhitelist: newImgWhitelist(db, opts...),
		Message:      newMessage(db, opts...),
		MsgTopic:     newMsgTopic(db, opts...),
		MsgWord:      newMsgWord(db, opts...),
		Topic:        newTopic(db, opts...),
		User:         newUser(db, opts...),
		Word:         newWord(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AtUser       atUser
	Group        group
	Image        image
	ImgWhitelist imgWhitelist
	Message      message
	MsgTopic     msgTopic
	MsgWord      msgWord
	Topic        topic
	User         user
	Word         word
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		AtUser:       q.AtUser.clone(db),
		Group:        q.Group.clone(db),
		Image:        q.Image.clone(db),
		ImgWhitelist: q.ImgWhitelist.clone(db),
		Message:      q.Message.clone(db),
		MsgTopic:     q.MsgTopic.clone(db),
		MsgWord:      q.MsgWord.clone(db),
		Topic:        q.Topic.clone(db),
		User:         q.User.clone(db),
		Word:         q.Word.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		AtUser:       q.AtUser.replaceDB(db),
		Group:        q.Group.replaceDB(db),
		Image:        q.Image.replaceDB(db),
		ImgWhitelist: q.ImgWhitelist.replaceDB(db),
		Message:      q.Message.replaceDB(db),
		MsgTopic:     q.MsgTopic.replaceDB(db),
		MsgWord:      q.MsgWord.replaceDB(db),
		Topic:        q.Topic.replaceDB(db),
		User:         q.User.replaceDB(db),
		Word:         q.Word.replaceDB(db),
	}
}

type queryCtx struct {
	AtUser       IAtUserDo
	Group        IGroupDo
	Image        IImageDo
	ImgWhitelist IImgWhitelistDo
	Message      IMessageDo
	MsgTopic     IMsgTopicDo
	MsgWord      IMsgWordDo
	Topic        ITopicDo
	User         IUserDo
	Word         IWordDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AtUser:       q.AtUser.WithContext(ctx),
		Group:        q.Group.WithContext(ctx),
		Image:        q.Image.WithContext(ctx),
		ImgWhitelist: q.ImgWhitelist.WithContext(ctx),
		Message:      q.Message.WithContext(ctx),
		MsgTopic:     q.MsgTopic.WithContext(ctx),
		MsgWord:      q.MsgWord.WithContext(ctx),
		Topic:        q.Topic.WithContext(ctx),
		User:         q.User.WithContext(ctx),
		Word:         q.Word.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
