// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"njk_go/internal/model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newImgWhitelist(db *gorm.DB, opts ...gen.DOOption) imgWhitelist {
	_imgWhitelist := imgWhitelist{}

	_imgWhitelist.imgWhitelistDo.UseDB(db, opts...)
	_imgWhitelist.imgWhitelistDo.UseModel(&model.ImgWhitelist{})

	tableName := _imgWhitelist.imgWhitelistDo.TableName()
	_imgWhitelist.ALL = field.NewAsterisk(tableName)
	_imgWhitelist.ID = field.NewInt32(tableName, "id")
	_imgWhitelist.ImageHash = field.NewString(tableName, "image_hash")

	_imgWhitelist.fillFieldMap()

	return _imgWhitelist
}

type imgWhitelist struct {
	imgWhitelistDo imgWhitelistDo

	ALL       field.Asterisk
	ID        field.Int32
	ImageHash field.String

	fieldMap map[string]field.Expr
}

func (i imgWhitelist) Table(newTableName string) *imgWhitelist {
	i.imgWhitelistDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i imgWhitelist) As(alias string) *imgWhitelist {
	i.imgWhitelistDo.DO = *(i.imgWhitelistDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *imgWhitelist) updateTableName(table string) *imgWhitelist {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt32(table, "id")
	i.ImageHash = field.NewString(table, "image_hash")

	i.fillFieldMap()

	return i
}

func (i *imgWhitelist) WithContext(ctx context.Context) IImgWhitelistDo {
	return i.imgWhitelistDo.WithContext(ctx)
}

func (i imgWhitelist) TableName() string { return i.imgWhitelistDo.TableName() }

func (i imgWhitelist) Alias() string { return i.imgWhitelistDo.Alias() }

func (i imgWhitelist) Columns(cols ...field.Expr) gen.Columns {
	return i.imgWhitelistDo.Columns(cols...)
}

func (i *imgWhitelist) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *imgWhitelist) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 2)
	i.fieldMap["id"] = i.ID
	i.fieldMap["image_hash"] = i.ImageHash
}

func (i imgWhitelist) clone(db *gorm.DB) imgWhitelist {
	i.imgWhitelistDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i imgWhitelist) replaceDB(db *gorm.DB) imgWhitelist {
	i.imgWhitelistDo.ReplaceDB(db)
	return i
}

type imgWhitelistDo struct{ gen.DO }

type IImgWhitelistDo interface {
	gen.SubQuery
	Debug() IImgWhitelistDo
	WithContext(ctx context.Context) IImgWhitelistDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IImgWhitelistDo
	WriteDB() IImgWhitelistDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IImgWhitelistDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IImgWhitelistDo
	Not(conds ...gen.Condition) IImgWhitelistDo
	Or(conds ...gen.Condition) IImgWhitelistDo
	Select(conds ...field.Expr) IImgWhitelistDo
	Where(conds ...gen.Condition) IImgWhitelistDo
	Order(conds ...field.Expr) IImgWhitelistDo
	Distinct(cols ...field.Expr) IImgWhitelistDo
	Omit(cols ...field.Expr) IImgWhitelistDo
	Join(table schema.Tabler, on ...field.Expr) IImgWhitelistDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IImgWhitelistDo
	RightJoin(table schema.Tabler, on ...field.Expr) IImgWhitelistDo
	Group(cols ...field.Expr) IImgWhitelistDo
	Having(conds ...gen.Condition) IImgWhitelistDo
	Limit(limit int) IImgWhitelistDo
	Offset(offset int) IImgWhitelistDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IImgWhitelistDo
	Unscoped() IImgWhitelistDo
	Create(values ...*model.ImgWhitelist) error
	CreateInBatches(values []*model.ImgWhitelist, batchSize int) error
	Save(values ...*model.ImgWhitelist) error
	First() (*model.ImgWhitelist, error)
	Take() (*model.ImgWhitelist, error)
	Last() (*model.ImgWhitelist, error)
	Find() ([]*model.ImgWhitelist, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ImgWhitelist, err error)
	FindInBatches(result *[]*model.ImgWhitelist, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ImgWhitelist) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IImgWhitelistDo
	Assign(attrs ...field.AssignExpr) IImgWhitelistDo
	Joins(fields ...field.RelationField) IImgWhitelistDo
	Preload(fields ...field.RelationField) IImgWhitelistDo
	FirstOrInit() (*model.ImgWhitelist, error)
	FirstOrCreate() (*model.ImgWhitelist, error)
	FindByPage(offset int, limit int) (result []*model.ImgWhitelist, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IImgWhitelistDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i imgWhitelistDo) Debug() IImgWhitelistDo {
	return i.withDO(i.DO.Debug())
}

func (i imgWhitelistDo) WithContext(ctx context.Context) IImgWhitelistDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i imgWhitelistDo) ReadDB() IImgWhitelistDo {
	return i.Clauses(dbresolver.Read)
}

func (i imgWhitelistDo) WriteDB() IImgWhitelistDo {
	return i.Clauses(dbresolver.Write)
}

func (i imgWhitelistDo) Session(config *gorm.Session) IImgWhitelistDo {
	return i.withDO(i.DO.Session(config))
}

func (i imgWhitelistDo) Clauses(conds ...clause.Expression) IImgWhitelistDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i imgWhitelistDo) Returning(value interface{}, columns ...string) IImgWhitelistDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i imgWhitelistDo) Not(conds ...gen.Condition) IImgWhitelistDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i imgWhitelistDo) Or(conds ...gen.Condition) IImgWhitelistDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i imgWhitelistDo) Select(conds ...field.Expr) IImgWhitelistDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i imgWhitelistDo) Where(conds ...gen.Condition) IImgWhitelistDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i imgWhitelistDo) Order(conds ...field.Expr) IImgWhitelistDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i imgWhitelistDo) Distinct(cols ...field.Expr) IImgWhitelistDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i imgWhitelistDo) Omit(cols ...field.Expr) IImgWhitelistDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i imgWhitelistDo) Join(table schema.Tabler, on ...field.Expr) IImgWhitelistDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i imgWhitelistDo) LeftJoin(table schema.Tabler, on ...field.Expr) IImgWhitelistDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i imgWhitelistDo) RightJoin(table schema.Tabler, on ...field.Expr) IImgWhitelistDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i imgWhitelistDo) Group(cols ...field.Expr) IImgWhitelistDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i imgWhitelistDo) Having(conds ...gen.Condition) IImgWhitelistDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i imgWhitelistDo) Limit(limit int) IImgWhitelistDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i imgWhitelistDo) Offset(offset int) IImgWhitelistDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i imgWhitelistDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IImgWhitelistDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i imgWhitelistDo) Unscoped() IImgWhitelistDo {
	return i.withDO(i.DO.Unscoped())
}

func (i imgWhitelistDo) Create(values ...*model.ImgWhitelist) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i imgWhitelistDo) CreateInBatches(values []*model.ImgWhitelist, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i imgWhitelistDo) Save(values ...*model.ImgWhitelist) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i imgWhitelistDo) First() (*model.ImgWhitelist, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImgWhitelist), nil
	}
}

func (i imgWhitelistDo) Take() (*model.ImgWhitelist, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImgWhitelist), nil
	}
}

func (i imgWhitelistDo) Last() (*model.ImgWhitelist, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImgWhitelist), nil
	}
}

func (i imgWhitelistDo) Find() ([]*model.ImgWhitelist, error) {
	result, err := i.DO.Find()
	return result.([]*model.ImgWhitelist), err
}

func (i imgWhitelistDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ImgWhitelist, err error) {
	buf := make([]*model.ImgWhitelist, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i imgWhitelistDo) FindInBatches(result *[]*model.ImgWhitelist, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i imgWhitelistDo) Attrs(attrs ...field.AssignExpr) IImgWhitelistDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i imgWhitelistDo) Assign(attrs ...field.AssignExpr) IImgWhitelistDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i imgWhitelistDo) Joins(fields ...field.RelationField) IImgWhitelistDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i imgWhitelistDo) Preload(fields ...field.RelationField) IImgWhitelistDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i imgWhitelistDo) FirstOrInit() (*model.ImgWhitelist, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImgWhitelist), nil
	}
}

func (i imgWhitelistDo) FirstOrCreate() (*model.ImgWhitelist, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImgWhitelist), nil
	}
}

func (i imgWhitelistDo) FindByPage(offset int, limit int) (result []*model.ImgWhitelist, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i imgWhitelistDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i imgWhitelistDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i imgWhitelistDo) Delete(models ...*model.ImgWhitelist) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *imgWhitelistDo) withDO(do gen.Dao) *imgWhitelistDo {
	i.DO = *do.(*gen.DO)
	return i
}
