// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"njk_go/internal/model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMsgWord(db *gorm.DB, opts ...gen.DOOption) msgWord {
	_msgWord := msgWord{}

	_msgWord.msgWordDo.UseDB(db, opts...)
	_msgWord.msgWordDo.UseModel(&model.MsgWord{})

	tableName := _msgWord.msgWordDo.TableName()
	_msgWord.ALL = field.NewAsterisk(tableName)
	_msgWord.ID = field.NewInt32(tableName, "id")
	_msgWord.MessageID = field.NewString(tableName, "message_id")
	_msgWord.WordID = field.NewInt32(tableName, "word_id")

	_msgWord.fillFieldMap()

	return _msgWord
}

type msgWord struct {
	msgWordDo msgWordDo

	ALL       field.Asterisk
	ID        field.Int32
	MessageID field.String
	WordID    field.Int32

	fieldMap map[string]field.Expr
}

func (m msgWord) Table(newTableName string) *msgWord {
	m.msgWordDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m msgWord) As(alias string) *msgWord {
	m.msgWordDo.DO = *(m.msgWordDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *msgWord) updateTableName(table string) *msgWord {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt32(table, "id")
	m.MessageID = field.NewString(table, "message_id")
	m.WordID = field.NewInt32(table, "word_id")

	m.fillFieldMap()

	return m
}

func (m *msgWord) WithContext(ctx context.Context) IMsgWordDo { return m.msgWordDo.WithContext(ctx) }

func (m msgWord) TableName() string { return m.msgWordDo.TableName() }

func (m msgWord) Alias() string { return m.msgWordDo.Alias() }

func (m msgWord) Columns(cols ...field.Expr) gen.Columns { return m.msgWordDo.Columns(cols...) }

func (m *msgWord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *msgWord) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 3)
	m.fieldMap["id"] = m.ID
	m.fieldMap["message_id"] = m.MessageID
	m.fieldMap["word_id"] = m.WordID
}

func (m msgWord) clone(db *gorm.DB) msgWord {
	m.msgWordDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m msgWord) replaceDB(db *gorm.DB) msgWord {
	m.msgWordDo.ReplaceDB(db)
	return m
}

type msgWordDo struct{ gen.DO }

type IMsgWordDo interface {
	gen.SubQuery
	Debug() IMsgWordDo
	WithContext(ctx context.Context) IMsgWordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMsgWordDo
	WriteDB() IMsgWordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMsgWordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMsgWordDo
	Not(conds ...gen.Condition) IMsgWordDo
	Or(conds ...gen.Condition) IMsgWordDo
	Select(conds ...field.Expr) IMsgWordDo
	Where(conds ...gen.Condition) IMsgWordDo
	Order(conds ...field.Expr) IMsgWordDo
	Distinct(cols ...field.Expr) IMsgWordDo
	Omit(cols ...field.Expr) IMsgWordDo
	Join(table schema.Tabler, on ...field.Expr) IMsgWordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMsgWordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMsgWordDo
	Group(cols ...field.Expr) IMsgWordDo
	Having(conds ...gen.Condition) IMsgWordDo
	Limit(limit int) IMsgWordDo
	Offset(offset int) IMsgWordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMsgWordDo
	Unscoped() IMsgWordDo
	Create(values ...*model.MsgWord) error
	CreateInBatches(values []*model.MsgWord, batchSize int) error
	Save(values ...*model.MsgWord) error
	First() (*model.MsgWord, error)
	Take() (*model.MsgWord, error)
	Last() (*model.MsgWord, error)
	Find() ([]*model.MsgWord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MsgWord, err error)
	FindInBatches(result *[]*model.MsgWord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MsgWord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMsgWordDo
	Assign(attrs ...field.AssignExpr) IMsgWordDo
	Joins(fields ...field.RelationField) IMsgWordDo
	Preload(fields ...field.RelationField) IMsgWordDo
	FirstOrInit() (*model.MsgWord, error)
	FirstOrCreate() (*model.MsgWord, error)
	FindByPage(offset int, limit int) (result []*model.MsgWord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMsgWordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m msgWordDo) Debug() IMsgWordDo {
	return m.withDO(m.DO.Debug())
}

func (m msgWordDo) WithContext(ctx context.Context) IMsgWordDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m msgWordDo) ReadDB() IMsgWordDo {
	return m.Clauses(dbresolver.Read)
}

func (m msgWordDo) WriteDB() IMsgWordDo {
	return m.Clauses(dbresolver.Write)
}

func (m msgWordDo) Session(config *gorm.Session) IMsgWordDo {
	return m.withDO(m.DO.Session(config))
}

func (m msgWordDo) Clauses(conds ...clause.Expression) IMsgWordDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m msgWordDo) Returning(value interface{}, columns ...string) IMsgWordDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m msgWordDo) Not(conds ...gen.Condition) IMsgWordDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m msgWordDo) Or(conds ...gen.Condition) IMsgWordDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m msgWordDo) Select(conds ...field.Expr) IMsgWordDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m msgWordDo) Where(conds ...gen.Condition) IMsgWordDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m msgWordDo) Order(conds ...field.Expr) IMsgWordDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m msgWordDo) Distinct(cols ...field.Expr) IMsgWordDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m msgWordDo) Omit(cols ...field.Expr) IMsgWordDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m msgWordDo) Join(table schema.Tabler, on ...field.Expr) IMsgWordDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m msgWordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMsgWordDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m msgWordDo) RightJoin(table schema.Tabler, on ...field.Expr) IMsgWordDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m msgWordDo) Group(cols ...field.Expr) IMsgWordDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m msgWordDo) Having(conds ...gen.Condition) IMsgWordDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m msgWordDo) Limit(limit int) IMsgWordDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m msgWordDo) Offset(offset int) IMsgWordDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m msgWordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMsgWordDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m msgWordDo) Unscoped() IMsgWordDo {
	return m.withDO(m.DO.Unscoped())
}

func (m msgWordDo) Create(values ...*model.MsgWord) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m msgWordDo) CreateInBatches(values []*model.MsgWord, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m msgWordDo) Save(values ...*model.MsgWord) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m msgWordDo) First() (*model.MsgWord, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgWord), nil
	}
}

func (m msgWordDo) Take() (*model.MsgWord, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgWord), nil
	}
}

func (m msgWordDo) Last() (*model.MsgWord, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgWord), nil
	}
}

func (m msgWordDo) Find() ([]*model.MsgWord, error) {
	result, err := m.DO.Find()
	return result.([]*model.MsgWord), err
}

func (m msgWordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MsgWord, err error) {
	buf := make([]*model.MsgWord, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m msgWordDo) FindInBatches(result *[]*model.MsgWord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m msgWordDo) Attrs(attrs ...field.AssignExpr) IMsgWordDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m msgWordDo) Assign(attrs ...field.AssignExpr) IMsgWordDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m msgWordDo) Joins(fields ...field.RelationField) IMsgWordDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m msgWordDo) Preload(fields ...field.RelationField) IMsgWordDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m msgWordDo) FirstOrInit() (*model.MsgWord, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgWord), nil
	}
}

func (m msgWordDo) FirstOrCreate() (*model.MsgWord, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgWord), nil
	}
}

func (m msgWordDo) FindByPage(offset int, limit int) (result []*model.MsgWord, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m msgWordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m msgWordDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m msgWordDo) Delete(models ...*model.MsgWord) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *msgWordDo) withDO(do gen.Dao) *msgWordDo {
	m.DO = *do.(*gen.DO)
	return m
}
