// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"njk_go/internal/model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMsgTopic(db *gorm.DB, opts ...gen.DOOption) msgTopic {
	_msgTopic := msgTopic{}

	_msgTopic.msgTopicDo.UseDB(db, opts...)
	_msgTopic.msgTopicDo.UseModel(&model.MsgTopic{})

	tableName := _msgTopic.msgTopicDo.TableName()
	_msgTopic.ALL = field.NewAsterisk(tableName)
	_msgTopic.ID = field.NewInt32(tableName, "id")
	_msgTopic.MessageID = field.NewString(tableName, "message_id")
	_msgTopic.TopicID = field.NewInt32(tableName, "topic_id")

	_msgTopic.fillFieldMap()

	return _msgTopic
}

type msgTopic struct {
	msgTopicDo msgTopicDo

	ALL       field.Asterisk
	ID        field.Int32
	MessageID field.String
	TopicID   field.Int32

	fieldMap map[string]field.Expr
}

func (m msgTopic) Table(newTableName string) *msgTopic {
	m.msgTopicDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m msgTopic) As(alias string) *msgTopic {
	m.msgTopicDo.DO = *(m.msgTopicDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *msgTopic) updateTableName(table string) *msgTopic {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt32(table, "id")
	m.MessageID = field.NewString(table, "message_id")
	m.TopicID = field.NewInt32(table, "topic_id")

	m.fillFieldMap()

	return m
}

func (m *msgTopic) WithContext(ctx context.Context) IMsgTopicDo { return m.msgTopicDo.WithContext(ctx) }

func (m msgTopic) TableName() string { return m.msgTopicDo.TableName() }

func (m msgTopic) Alias() string { return m.msgTopicDo.Alias() }

func (m msgTopic) Columns(cols ...field.Expr) gen.Columns { return m.msgTopicDo.Columns(cols...) }

func (m *msgTopic) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *msgTopic) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 3)
	m.fieldMap["id"] = m.ID
	m.fieldMap["message_id"] = m.MessageID
	m.fieldMap["topic_id"] = m.TopicID
}

func (m msgTopic) clone(db *gorm.DB) msgTopic {
	m.msgTopicDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m msgTopic) replaceDB(db *gorm.DB) msgTopic {
	m.msgTopicDo.ReplaceDB(db)
	return m
}

type msgTopicDo struct{ gen.DO }

type IMsgTopicDo interface {
	gen.SubQuery
	Debug() IMsgTopicDo
	WithContext(ctx context.Context) IMsgTopicDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMsgTopicDo
	WriteDB() IMsgTopicDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMsgTopicDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMsgTopicDo
	Not(conds ...gen.Condition) IMsgTopicDo
	Or(conds ...gen.Condition) IMsgTopicDo
	Select(conds ...field.Expr) IMsgTopicDo
	Where(conds ...gen.Condition) IMsgTopicDo
	Order(conds ...field.Expr) IMsgTopicDo
	Distinct(cols ...field.Expr) IMsgTopicDo
	Omit(cols ...field.Expr) IMsgTopicDo
	Join(table schema.Tabler, on ...field.Expr) IMsgTopicDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMsgTopicDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMsgTopicDo
	Group(cols ...field.Expr) IMsgTopicDo
	Having(conds ...gen.Condition) IMsgTopicDo
	Limit(limit int) IMsgTopicDo
	Offset(offset int) IMsgTopicDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMsgTopicDo
	Unscoped() IMsgTopicDo
	Create(values ...*model.MsgTopic) error
	CreateInBatches(values []*model.MsgTopic, batchSize int) error
	Save(values ...*model.MsgTopic) error
	First() (*model.MsgTopic, error)
	Take() (*model.MsgTopic, error)
	Last() (*model.MsgTopic, error)
	Find() ([]*model.MsgTopic, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MsgTopic, err error)
	FindInBatches(result *[]*model.MsgTopic, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MsgTopic) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMsgTopicDo
	Assign(attrs ...field.AssignExpr) IMsgTopicDo
	Joins(fields ...field.RelationField) IMsgTopicDo
	Preload(fields ...field.RelationField) IMsgTopicDo
	FirstOrInit() (*model.MsgTopic, error)
	FirstOrCreate() (*model.MsgTopic, error)
	FindByPage(offset int, limit int) (result []*model.MsgTopic, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMsgTopicDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m msgTopicDo) Debug() IMsgTopicDo {
	return m.withDO(m.DO.Debug())
}

func (m msgTopicDo) WithContext(ctx context.Context) IMsgTopicDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m msgTopicDo) ReadDB() IMsgTopicDo {
	return m.Clauses(dbresolver.Read)
}

func (m msgTopicDo) WriteDB() IMsgTopicDo {
	return m.Clauses(dbresolver.Write)
}

func (m msgTopicDo) Session(config *gorm.Session) IMsgTopicDo {
	return m.withDO(m.DO.Session(config))
}

func (m msgTopicDo) Clauses(conds ...clause.Expression) IMsgTopicDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m msgTopicDo) Returning(value interface{}, columns ...string) IMsgTopicDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m msgTopicDo) Not(conds ...gen.Condition) IMsgTopicDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m msgTopicDo) Or(conds ...gen.Condition) IMsgTopicDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m msgTopicDo) Select(conds ...field.Expr) IMsgTopicDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m msgTopicDo) Where(conds ...gen.Condition) IMsgTopicDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m msgTopicDo) Order(conds ...field.Expr) IMsgTopicDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m msgTopicDo) Distinct(cols ...field.Expr) IMsgTopicDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m msgTopicDo) Omit(cols ...field.Expr) IMsgTopicDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m msgTopicDo) Join(table schema.Tabler, on ...field.Expr) IMsgTopicDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m msgTopicDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMsgTopicDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m msgTopicDo) RightJoin(table schema.Tabler, on ...field.Expr) IMsgTopicDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m msgTopicDo) Group(cols ...field.Expr) IMsgTopicDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m msgTopicDo) Having(conds ...gen.Condition) IMsgTopicDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m msgTopicDo) Limit(limit int) IMsgTopicDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m msgTopicDo) Offset(offset int) IMsgTopicDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m msgTopicDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMsgTopicDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m msgTopicDo) Unscoped() IMsgTopicDo {
	return m.withDO(m.DO.Unscoped())
}

func (m msgTopicDo) Create(values ...*model.MsgTopic) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m msgTopicDo) CreateInBatches(values []*model.MsgTopic, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m msgTopicDo) Save(values ...*model.MsgTopic) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m msgTopicDo) First() (*model.MsgTopic, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgTopic), nil
	}
}

func (m msgTopicDo) Take() (*model.MsgTopic, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgTopic), nil
	}
}

func (m msgTopicDo) Last() (*model.MsgTopic, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgTopic), nil
	}
}

func (m msgTopicDo) Find() ([]*model.MsgTopic, error) {
	result, err := m.DO.Find()
	return result.([]*model.MsgTopic), err
}

func (m msgTopicDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MsgTopic, err error) {
	buf := make([]*model.MsgTopic, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m msgTopicDo) FindInBatches(result *[]*model.MsgTopic, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m msgTopicDo) Attrs(attrs ...field.AssignExpr) IMsgTopicDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m msgTopicDo) Assign(attrs ...field.AssignExpr) IMsgTopicDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m msgTopicDo) Joins(fields ...field.RelationField) IMsgTopicDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m msgTopicDo) Preload(fields ...field.RelationField) IMsgTopicDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m msgTopicDo) FirstOrInit() (*model.MsgTopic, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgTopic), nil
	}
}

func (m msgTopicDo) FirstOrCreate() (*model.MsgTopic, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgTopic), nil
	}
}

func (m msgTopicDo) FindByPage(offset int, limit int) (result []*model.MsgTopic, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m msgTopicDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m msgTopicDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m msgTopicDo) Delete(models ...*model.MsgTopic) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *msgTopicDo) withDO(do gen.Dao) *msgTopicDo {
	m.DO = *do.(*gen.DO)
	return m
}
